import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`text-teal-400 drop-shadow-md drop-shadow-[0_1.4px_1.4px_rgba(0,0,0,0.8)] bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-700 to-purple-900 ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
